### ISSUE TITLE
Dependency on 'byebug'

### ISSUE THREAD

**Issue by nikitsaraf** [byroot/derrick#1]
Is the dependency on the 'byebug' gem really needed ? https://github.com/byroot/derrick/blob/master/lib/derrick/cli.rb#L4

This will not allow the installation of 'derrick' running on ruby 1.9.3 like mine, as 'byebug' is ruby 2 debugger.

**Comment by byroot** [comment]
Hi. I'm really sorry this notification have been lost in the wild. The byebug dependency is a total mistake I'll fix it.

**Comment by byroot** [comment]
Fixed by https://github.com/byroot/derrick/commit/9e8404493f77f0714465b4c85bad8b9ab1dd615b
